name: Test

on:
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: bun/action-setup@v2.2.4
        name: Install bun
        id: bun-install
        with:
          version: 8.6.1
          run_install: false

      - name: Get bun store directory
        id: bun-cache
        run: |
          echo "bun_cache_dir=$(bun store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup bun cache
        with:
          path: ${{ steps.bun-cache.outputs.bun_cache_dir }}
          key: ${{ runner.os }}-bun-store-${{ hashFiles('**/bun-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-bun-store-
      - name: Install dependencies
        run: bun install

      - run: bun test
